export const RouteNames = {
  Login: "Login",
  ForgotPassword: "ForgotPassword",
  Dashboard: "Dashboard",
  QuickCapture: "QuickCapture",
  TaskReview: "TaskReview",
  CameraCapture: "CameraCapture",
  Review: "Review",
  TaskDetails: "TaskDetails",
  Settings: "Settings",
  Profile: "Profile",
  MainTabs: "MainTabs",
  PrivacyConsent: "PrivacyConsent",
  PrivacyPolicy: "PrivacyPolicy",
  HelpFaq: "HelpFaq",
} as const;
